### PR TITLE
Binding for triangular_sequence

### PR DESCRIPTION
**Pull request by pkopparla**
Addresses #1 
Binding for the `triangular_sequence` function and some simple unit tests. Please see `README.md` for instructions on installation and testing. Comments on code structure and features welcome.

### CODE REVIEW

**Review by Robinlovelace — COMMENTED** [review]
Not tested this, looking forward to doing so ASAP! I suspect @dabreegster is a better person to review this than me, with more experience of programming in Python and Rust.

**Comment by pkopparla** [comment]
@Robinlovelace Could I ask a question on the `Params` struct? The wrapper for the`clockboard` function will receive `params` as a python dictionary and I'm try to figure out how to feed that into the `Params` rust struct. The struct seems to only read-in arguments from command line. I tried initiating a default `Param` object and updating the inner fields (`num_segments` etc) from the dictionary but these are private and can't be accessed. Would you have any advice on how to tackle this?

**Comment by Robinlovelace** [comment]
I'm not sure but imagine that the Python-Rust interface library can convert form a Python dictionary into a Struct, no?

**Comment by pkopparla** [comment]
Yes, the trouble is there is no setter method for `Params`. I tried making a simple example within `zonebuilder-rust/examples/param-example.rs` as follows:
```rust
use zonebuilder::{Params,triangular_sequence};
fn main() {
    let s = Params {
        num_segments: 12,
        distances: triangular_sequence(3),
        num_vertices_arc: 11,
        precision: 4,
        projected: true,
    };
    println!("{:?}",&s);
}
```
This fails by saying that the fields are private. There is no way to create a new `Params` object except with default or command-line args read-in. A setter or new method, or public fields would be very useful.

**Comment by dabreegster** [comment]
> A setter or new method, or public fields would be very useful.

Whoops, total oversight on my part. https://github.com/zonebuilders/zonebuilder-rust/commit/b3588689eb11f966ee6dc56e2f4c5416b819c533 should do the trick. You can temporarily do `zonebuilder = { git = "https://github.com/zonebuilders/zonebuilder-rust/" }`, since this new commit isn't part of a crates.io release yet. Let me know if that doesn't unblock you.

**Comment by pkopparla** [comment]
Thanks @dabreegster that seems to do the trick. I'm going to merge this and open a new PR for the clockboard stuff, maybe next week. There's a couple of things I want to get you guys thoughts on.

**Pull request merged**
